### ISSUE TITLE
Test DAQ that provides feeds

### ISSUE THREAD

**Issue by gregoavg** [feedsome/feedsome#1]
This issue requires the development of a new DAQ producer, capable of generating and providing data feeds,
in a continuous order.

The implementation of this DAQ is useful for testing purposes (dummy data, integration testing, behavior analysis), as it works as an trigger point, by producing data feeds for the system.

Finally, the structural components that will be used, should pass an evaluation process and potentially,
expose any forthcoming shared logic to a **daq-core** submodule.

- [ ] #2 Implement data feed generator
- [ ] #3 camel routes for message feeds
- [ ] #4 camel routes for plugin registration/management

**Comment by gregoavg** [comment]
all sub-tasks completed: closing issue!
